namespace: sandbox

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP

deployment:
  image: abszissex/techtrends
  imageTag: latest
  imagePullPolicy: IfNotPresent
  replicas: 1 
  resources:
    requests:
      memory: 64Mi
      cpu: 250m
    limits:
      memory: 128Mi
      cpu: 500m
  containerPort: 3111
  livenessProbePath: /healthz
  readinessProbePath: /healthz